spring:
  #数据库配置
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.140.130:1521:orcl
    username: senyintccvd
    password: senyintccvd
    druid:
      #初始化连接大小
      initial-size: 3
      #最小空闲连接数
      min-idle: 2
      #最大连接数
      max-active: 20
      validationQuery: SELECT 1 FROM DUAL
      filters: stat
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-wait: 30000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true